directive @auth(requires: Role = ADMIN) on OBJECT | FIELD_DEFINITION

scalar DateTime

enum Role {
  ADMIN
  USER
}

input createUserInput {
  name: String
  email: String!
  role: String
  provider: String!
  socialId: String!
}

input loginUserInput {
  name: String
  socialId: String!
  provider: String!
  email: String!
}

type Mutation {
  add(x: Int!, y: Int!): Int!
  createUser(user: createUserInput!): User!
}

type Query {
  dogs(word: String): String!
  user(id: Int!): User! @auth(requires: ADMIN)
  users: [User]! @auth(requires: ADMIN)
  login(input: loginUserInput!): Tokens
  refresh(refreshToken: String!): GeneratedTokens!
}

type GeneratedTokens {
  accessToken: String
  refreshToken: String!
}

type User {
  id: Int!
  name: String
  provider: String!
  socialId: String!
  email: String!
  role: String
  createdAt: DateTime!
  updatedAt: DateTime!
}

type Tokens {
  id: Int!
  userId: Int!
  refreshToken: String!
  createdAt: DateTime
  updatedAt: DateTime
}
